### ISSUE TITLE
Please add instructions on how to install the theme/plugin/whatever.

### ISSUE THREAD

**Issue by martinandersson** [xinkunZ/NotReallyMDTheme#1]
After installation nothing at all is changed appearance-wise. Nor can I find anywhere instructions telling me to do something.

**Comment by martinandersson** [comment]
Okay my bad. It's installed as a plugin but it's really a theme. One has to go into settings and activate the theme:

![Capture](https://user-images.githubusercontent.com/1541819/58632233-477ce580-82e5-11e9-8127-7dd560ec6be2.PNG)

I know, it's retarded that themes are installed as "plugins". But hey, that's the modern software reality we have to deal with. Everyone keeps layering shit on top of shit until nothing makes sense any more. But for you as a "plugin" developer it would be very beneficial to the community if you added this "installation instruction" somewhere. Thanx!

**Comment by xinkunZ** [comment]
* Uh... this is a new feature in IDEA 2019.1, please see [Jetbrains's blog](https://blog.jetbrains.com/idea/2019/03/brighten-up-your-day-add-color-to-intellij-idea/) how to use it!😂
* I thought every developer who use IDEA will read each blog pushed by Jetbrains.

**Comment by xinkunZ** [comment]
* fix
